"""repo tracking_mode and summary_depth

Revision ID: 48b7354e1931
Revises: 015e45a48b54
Create Date: 2026-06-19 15:08:08.952002
"""
from alembic import op
import sqlalchemy as sa


revision = '48b7354e1931'
down_revision = '015e45a48b54'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # server_default backfills existing rows; keeps the column NOT NULL.
    op.add_column(
        'repositories',
        sa.Column('tracking_mode', sa.String(), nullable=False, server_default='all'),
    )
    op.add_column(
        'repositories',
        sa.Column('summary_depth', sa.String(), nullable=False, server_default='technical'),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('repositories', 'summary_depth')
    op.drop_column('repositories', 'tracking_mode')
    # ### end Alembic commands ###
