"""user timezone

Revision ID: 62a438b77381
Revises: 48b7354e1931
Create Date: 2026-06-19 16:09:47.284226
"""
from alembic import op
import sqlalchemy as sa


revision = '62a438b77381'
down_revision = '48b7354e1931'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'users',
        sa.Column('timezone', sa.String(), nullable=False, server_default='Europe/Moscow'),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'timezone')
    # ### end Alembic commands ###
